-- =====================================================================
-- 0022_seed_geography_languages
-- Seed des referentiels geographiques et linguistiques.
--   * subregions : decoupage UNSD retenu par D-64 (10 sous-regions).
--   * countries  : ISO 3166-1 alpha-2, libelles francais, rattaches a
--                  leur sous-region UNSD.
--   * languages  : doc 20 Partie F (8 langues).
-- Reference : docs/decisions.md D-64 ; docs/db-conventions.md sections 1 et 4.
-- Migration de DONNEES uniquement : aucun DDL, aucune modification de RLS.
-- Rejouable : toutes les insertions sont en `on conflict do nothing`.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Sous-regions (D-64)
-- ---------------------------------------------------------------------
insert into public.subregions (code, name_fr, name_en, region_code, region_fr, sort_order) values
  ('africa-west', 'Afrique de l''Ouest', 'Western Africa', 'africa', 'Afrique', 10),
  ('africa-central', 'Afrique centrale', 'Middle Africa', 'africa', 'Afrique', 20),
  ('africa-east', 'Afrique de l''Est', 'Eastern Africa', 'africa', 'Afrique', 30),
  ('africa-south', 'Afrique australe', 'Southern Africa', 'africa', 'Afrique', 40),
  ('africa-north', 'Afrique du Nord', 'Northern Africa', 'africa', 'Afrique', 50),
  ('europe', 'Europe', 'Europe', 'europe', 'Europe', 60),
  ('america-north', 'Amérique du Nord', 'Northern America', 'americas', 'Amériques', 70),
  ('america-latin-caribbean', 'Amérique latine et Caraïbes', 'Latin America and the Caribbean', 'americas', 'Amériques', 80),
  ('asia', 'Asie', 'Asia', 'asia', 'Asie', 90),
  ('oceania', 'Océanie', 'Oceania', 'oceania', 'Océanie', 100)
on conflict (code) do nothing;

-- ---------------------------------------------------------------------
-- 2. Pays ISO 3166-1 alpha-2 (249 codes officiellement attribues)
--    `AQ` (Antarctique) n'appartient a aucune sous-region UNSD : il est
--    insere inactif, sans sous-region, pour que le referentiel ISO reste
--    complet sans polluer les filtres de matching.
-- ---------------------------------------------------------------------
insert into public.countries (code, name_fr, name_en, subregion_code, is_active) values
  ('AD', 'Andorre', 'Andorra', 'europe', true),
  ('AE', 'Émirats arabes unis', 'United Arab Emirates', 'asia', true),
  ('AF', 'Afghanistan', 'Afghanistan', 'asia', true),
  ('AG', 'Antigua-et-Barbuda', 'Antigua and Barbuda', 'america-latin-caribbean', true),
  ('AI', 'Anguilla', 'Anguilla', 'america-latin-caribbean', true),
  ('AL', 'Albanie', 'Albania', 'europe', true),
  ('AM', 'Arménie', 'Armenia', 'asia', true),
  ('AO', 'Angola', 'Angola', 'africa-central', true),
  ('AQ', 'Antarctique', 'Antarctica', null, false),
  ('AR', 'Argentine', 'Argentina', 'america-latin-caribbean', true),
  ('AS', 'Samoa américaines', 'American Samoa', 'oceania', true),
  ('AT', 'Autriche', 'Austria', 'europe', true),
  ('AU', 'Australie', 'Australia', 'oceania', true),
  ('AW', 'Aruba', 'Aruba', 'america-latin-caribbean', true),
  ('AX', 'Îles Åland', 'Åland Islands', 'europe', true),
  ('AZ', 'Azerbaïdjan', 'Azerbaijan', 'asia', true),
  ('BA', 'Bosnie-Herzégovine', 'Bosnia and Herzegovina', 'europe', true),
  ('BB', 'Barbade', 'Barbados', 'america-latin-caribbean', true),
  ('BD', 'Bangladesh', 'Bangladesh', 'asia', true),
  ('BE', 'Belgique', 'Belgium', 'europe', true),
  ('BF', 'Burkina Faso', 'Burkina Faso', 'africa-west', true),
  ('BG', 'Bulgarie', 'Bulgaria', 'europe', true),
  ('BH', 'Bahreïn', 'Bahrain', 'asia', true),
  ('BI', 'Burundi', 'Burundi', 'africa-east', true),
  ('BJ', 'Bénin', 'Benin', 'africa-west', true),
  ('BL', 'Saint-Barthélemy', 'Saint Barthélemy', 'america-latin-caribbean', true),
  ('BM', 'Bermudes', 'Bermuda', 'america-north', true),
  ('BN', 'Brunéi', 'Brunei Darussalam', 'asia', true),
  ('BO', 'Bolivie', 'Bolivia, Plurinational State of', 'america-latin-caribbean', true),
  ('BQ', 'Pays-Bas caribéens (Bonaire, Saint-Eustache et Saba)', 'Bonaire, Sint Eustatius and Saba', 'america-latin-caribbean', true),
  ('BR', 'Brésil', 'Brazil', 'america-latin-caribbean', true),
  ('BS', 'Bahamas', 'Bahamas', 'america-latin-caribbean', true),
  ('BT', 'Bhoutan', 'Bhutan', 'asia', true),
  ('BV', 'Île Bouvet', 'Bouvet Island', 'america-latin-caribbean', true),
  ('BW', 'Botswana', 'Botswana', 'africa-south', true),
  ('BY', 'Bélarus', 'Belarus', 'europe', true),
  ('BZ', 'Belize', 'Belize', 'america-latin-caribbean', true),
  ('CA', 'Canada', 'Canada', 'america-north', true),
  ('CC', 'Îles Cocos', 'Cocos (Keeling) Islands', 'oceania', true),
  ('CD', 'République démocratique du Congo', 'Congo, The Democratic Republic of the', 'africa-central', true),
  ('CF', 'République centrafricaine', 'Central African Republic', 'africa-central', true),
  ('CG', 'Congo', 'Congo', 'africa-central', true),
  ('CH', 'Suisse', 'Switzerland', 'europe', true),
  ('CI', 'Côte d''Ivoire', 'Côte d''Ivoire', 'africa-west', true),
  ('CK', 'Îles Cook', 'Cook Islands', 'oceania', true),
  ('CL', 'Chili', 'Chile', 'america-latin-caribbean', true),
  ('CM', 'Cameroun', 'Cameroon', 'africa-central', true),
  ('CN', 'Chine', 'China', 'asia', true),
  ('CO', 'Colombie', 'Colombia', 'america-latin-caribbean', true),
  ('CR', 'Costa Rica', 'Costa Rica', 'america-latin-caribbean', true),
  ('CU', 'Cuba', 'Cuba', 'america-latin-caribbean', true),
  ('CV', 'Cabo Verde', 'Cabo Verde', 'africa-west', true),
  ('CW', 'Curaçao', 'Curaçao', 'america-latin-caribbean', true),
  ('CX', 'Île Christmas', 'Christmas Island', 'oceania', true),
  ('CY', 'Chypre', 'Cyprus', 'asia', true),
  ('CZ', 'Tchéquie', 'Czechia', 'europe', true),
  ('DE', 'Allemagne', 'Germany', 'europe', true),
  ('DJ', 'Djibouti', 'Djibouti', 'africa-east', true),
  ('DK', 'Danemark', 'Denmark', 'europe', true),
  ('DM', 'Dominique', 'Dominica', 'america-latin-caribbean', true),
  ('DO', 'République dominicaine', 'Dominican Republic', 'america-latin-caribbean', true),
  ('DZ', 'Algérie', 'Algeria', 'africa-north', true),
  ('EC', 'Équateur', 'Ecuador', 'america-latin-caribbean', true),
  ('EE', 'Estonie', 'Estonia', 'europe', true),
  ('EG', 'Égypte', 'Egypt', 'africa-north', true),
  ('EH', 'Sahara occidental', 'Western Sahara', 'africa-north', true),
  ('ER', 'Érythrée', 'Eritrea', 'africa-east', true),
  ('ES', 'Espagne', 'Spain', 'europe', true),
  ('ET', 'Éthiopie', 'Ethiopia', 'africa-east', true),
  ('FI', 'Finlande', 'Finland', 'europe', true),
  ('FJ', 'Fidji', 'Fiji', 'oceania', true),
  ('FK', 'Îles Malouines', 'Falkland Islands (Malvinas)', 'america-latin-caribbean', true),
  ('FM', 'Micronésie', 'Micronesia, Federated States of', 'oceania', true),
  ('FO', 'Îles Féroé', 'Faroe Islands', 'europe', true),
  ('FR', 'France', 'France', 'europe', true),
  ('GA', 'Gabon', 'Gabon', 'africa-central', true),
  ('GB', 'Royaume-Uni', 'United Kingdom', 'europe', true),
  ('GD', 'Grenade', 'Grenada', 'america-latin-caribbean', true),
  ('GE', 'Géorgie', 'Georgia', 'asia', true),
  ('GF', 'Guyane française', 'French Guiana', 'america-latin-caribbean', true),
  ('GG', 'Guernesey', 'Guernsey', 'europe', true),
  ('GH', 'Ghana', 'Ghana', 'africa-west', true),
  ('GI', 'Gibraltar', 'Gibraltar', 'europe', true),
  ('GL', 'Groenland', 'Greenland', 'america-north', true),
  ('GM', 'Gambie', 'Gambia', 'africa-west', true),
  ('GN', 'Guinée', 'Guinea', 'africa-west', true),
  ('GP', 'Guadeloupe', 'Guadeloupe', 'america-latin-caribbean', true),
  ('GQ', 'Guinée équatoriale', 'Equatorial Guinea', 'africa-central', true),
  ('GR', 'Grèce', 'Greece', 'europe', true),
  ('GS', 'Géorgie du Sud-et-les Îles Sandwich du Sud', 'South Georgia and the South Sandwich Islands', 'america-latin-caribbean', true),
  ('GT', 'Guatemala', 'Guatemala', 'america-latin-caribbean', true),
  ('GU', 'Guam', 'Guam', 'oceania', true),
  ('GW', 'Guinée-Bissau', 'Guinea-Bissau', 'africa-west', true),
  ('GY', 'Guyana', 'Guyana', 'america-latin-caribbean', true),
  ('HK', 'Hong Kong', 'Hong Kong', 'asia', true),
  ('HM', 'Îles Heard-et-MacDonald', 'Heard Island and McDonald Islands', 'oceania', true),
  ('HN', 'Honduras', 'Honduras', 'america-latin-caribbean', true),
  ('HR', 'Croatie', 'Croatia', 'europe', true),
  ('HT', 'Haïti', 'Haiti', 'america-latin-caribbean', true),
  ('HU', 'Hongrie', 'Hungary', 'europe', true),
  ('ID', 'Indonésie', 'Indonesia', 'asia', true),
  ('IE', 'Irlande', 'Ireland', 'europe', true),
  ('IL', 'Israël', 'Israel', 'asia', true),
  ('IM', 'Île de Man', 'Isle of Man', 'europe', true),
  ('IN', 'Inde', 'India', 'asia', true),
  ('IO', 'Territoire britannique de l''océan Indien', 'British Indian Ocean Territory', 'africa-east', true),
  ('IQ', 'Irak', 'Iraq', 'asia', true),
  ('IR', 'Iran', 'Iran, Islamic Republic of', 'asia', true),
  ('IS', 'Islande', 'Iceland', 'europe', true),
  ('IT', 'Italie', 'Italy', 'europe', true),
  ('JE', 'Jersey', 'Jersey', 'europe', true),
  ('JM', 'Jamaïque', 'Jamaica', 'america-latin-caribbean', true),
  ('JO', 'Jordanie', 'Jordan', 'asia', true),
  ('JP', 'Japon', 'Japan', 'asia', true),
  ('KE', 'Kenya', 'Kenya', 'africa-east', true),
  ('KG', 'Kirghizistan', 'Kyrgyzstan', 'asia', true),
  ('KH', 'Cambodge', 'Cambodia', 'asia', true),
  ('KI', 'Kiribati', 'Kiribati', 'oceania', true),
  ('KM', 'Comores', 'Comoros', 'africa-east', true),
  ('KN', 'Saint-Christophe-et-Niévès', 'Saint Kitts and Nevis', 'america-latin-caribbean', true),
  ('KP', 'Corée du Nord', 'Korea, Democratic People''s Republic of', 'asia', true),
  ('KR', 'Corée du Sud', 'Korea, Republic of', 'asia', true),
  ('KW', 'Koweït', 'Kuwait', 'asia', true),
  ('KY', 'Îles Caïmans', 'Cayman Islands', 'america-latin-caribbean', true),
  ('KZ', 'Kazakhstan', 'Kazakhstan', 'asia', true),
  ('LA', 'Laos', 'Lao People''s Democratic Republic', 'asia', true),
  ('LB', 'Liban', 'Lebanon', 'asia', true),
  ('LC', 'Sainte-Lucie', 'Saint Lucia', 'america-latin-caribbean', true),
  ('LI', 'Liechtenstein', 'Liechtenstein', 'europe', true),
  ('LK', 'Sri Lanka', 'Sri Lanka', 'asia', true),
  ('LR', 'Libéria', 'Liberia', 'africa-west', true),
  ('LS', 'Lesotho', 'Lesotho', 'africa-south', true),
  ('LT', 'Lituanie', 'Lithuania', 'europe', true),
  ('LU', 'Luxembourg', 'Luxembourg', 'europe', true),
  ('LV', 'Lettonie', 'Latvia', 'europe', true),
  ('LY', 'Libye', 'Libya', 'africa-north', true),
  ('MA', 'Maroc', 'Morocco', 'africa-north', true),
  ('MC', 'Monaco', 'Monaco', 'europe', true),
  ('MD', 'Moldavie', 'Moldova, Republic of', 'europe', true),
  ('ME', 'Monténégro', 'Montenegro', 'europe', true),
  ('MF', 'Saint-Martin (partie française)', 'Saint Martin (French part)', 'america-latin-caribbean', true),
  ('MG', 'Madagascar', 'Madagascar', 'africa-east', true),
  ('MH', 'Îles Marshall', 'Marshall Islands', 'oceania', true),
  ('MK', 'Macédoine du Nord', 'North Macedonia', 'europe', true),
  ('ML', 'Mali', 'Mali', 'africa-west', true),
  ('MM', 'Birmanie', 'Myanmar', 'asia', true),
  ('MN', 'Mongolie', 'Mongolia', 'asia', true),
  ('MO', 'Macao', 'Macao', 'asia', true),
  ('MP', 'Îles Mariannes du Nord', 'Northern Mariana Islands', 'oceania', true),
  ('MQ', 'Martinique', 'Martinique', 'america-latin-caribbean', true),
  ('MR', 'Mauritanie', 'Mauritania', 'africa-west', true),
  ('MS', 'Montserrat', 'Montserrat', 'america-latin-caribbean', true),
  ('MT', 'Malte', 'Malta', 'europe', true),
  ('MU', 'Maurice', 'Mauritius', 'africa-east', true),
  ('MV', 'Maldives', 'Maldives', 'asia', true),
  ('MW', 'Malawi', 'Malawi', 'africa-east', true),
  ('MX', 'Mexique', 'Mexico', 'america-latin-caribbean', true),
  ('MY', 'Malaisie', 'Malaysia', 'asia', true),
  ('MZ', 'Mozambique', 'Mozambique', 'africa-east', true),
  ('NA', 'Namibie', 'Namibia', 'africa-south', true),
  ('NC', 'Nouvelle-Calédonie', 'New Caledonia', 'oceania', true),
  ('NE', 'Niger', 'Niger', 'africa-west', true),
  ('NF', 'Île Norfolk', 'Norfolk Island', 'oceania', true),
  ('NG', 'Nigeria', 'Nigeria', 'africa-west', true),
  ('NI', 'Nicaragua', 'Nicaragua', 'america-latin-caribbean', true),
  ('NL', 'Pays-Bas', 'Netherlands', 'europe', true),
  ('NO', 'Norvège', 'Norway', 'europe', true),
  ('NP', 'Népal', 'Nepal', 'asia', true),
  ('NR', 'Nauru', 'Nauru', 'oceania', true),
  ('NU', 'Nioue', 'Niue', 'oceania', true),
  ('NZ', 'Nouvelle-Zélande', 'New Zealand', 'oceania', true),
  ('OM', 'Oman', 'Oman', 'asia', true),
  ('PA', 'Panama', 'Panama', 'america-latin-caribbean', true),
  ('PE', 'Pérou', 'Peru', 'america-latin-caribbean', true),
  ('PF', 'Polynésie française', 'French Polynesia', 'oceania', true),
  ('PG', 'Papouasie-Nouvelle-Guinée', 'Papua New Guinea', 'oceania', true),
  ('PH', 'Philippines', 'Philippines', 'asia', true),
  ('PK', 'Pakistan', 'Pakistan', 'asia', true),
  ('PL', 'Pologne', 'Poland', 'europe', true),
  ('PM', 'Saint-Pierre-et-Miquelon', 'Saint Pierre and Miquelon', 'america-north', true),
  ('PN', 'Îles Pitcairn', 'Pitcairn', 'oceania', true),
  ('PR', 'Porto Rico', 'Puerto Rico', 'america-latin-caribbean', true),
  ('PS', 'Palestine', 'Palestine, State of', 'asia', true),
  ('PT', 'Portugal', 'Portugal', 'europe', true),
  ('PW', 'Palaos', 'Palau', 'oceania', true),
  ('PY', 'Paraguay', 'Paraguay', 'america-latin-caribbean', true),
  ('QA', 'Qatar', 'Qatar', 'asia', true),
  ('RE', 'La Réunion', 'Réunion', 'africa-east', true),
  ('RO', 'Roumanie', 'Romania', 'europe', true),
  ('RS', 'Serbie', 'Serbia', 'europe', true),
  ('RU', 'Russie', 'Russian Federation', 'europe', true),
  ('RW', 'Rwanda', 'Rwanda', 'africa-east', true),
  ('SA', 'Arabie saoudite', 'Saudi Arabia', 'asia', true),
  ('SB', 'Îles Salomon', 'Solomon Islands', 'oceania', true),
  ('SC', 'Seychelles', 'Seychelles', 'africa-east', true),
  ('SD', 'Soudan', 'Sudan', 'africa-north', true),
  ('SE', 'Suède', 'Sweden', 'europe', true),
  ('SG', 'Singapour', 'Singapore', 'asia', true),
  ('SH', 'Sainte-Hélène, Ascension et Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha', 'africa-west', true),
  ('SI', 'Slovénie', 'Slovenia', 'europe', true),
  ('SJ', 'Svalbard et Jan Mayen', 'Svalbard and Jan Mayen', 'europe', true),
  ('SK', 'Slovaquie', 'Slovakia', 'europe', true),
  ('SL', 'Sierra Leone', 'Sierra Leone', 'africa-west', true),
  ('SM', 'Saint-Marin', 'San Marino', 'europe', true),
  ('SN', 'Sénégal', 'Senegal', 'africa-west', true),
  ('SO', 'Somalie', 'Somalia', 'africa-east', true),
  ('SR', 'Suriname', 'Suriname', 'america-latin-caribbean', true),
  ('SS', 'Soudan du Sud', 'South Sudan', 'africa-east', true),
  ('ST', 'Sao Tomé-et-Principe', 'Sao Tome and Principe', 'africa-central', true),
  ('SV', 'Salvador', 'El Salvador', 'america-latin-caribbean', true),
  ('SX', 'Saint-Martin (partie néerlandaise)', 'Sint Maarten (Dutch part)', 'america-latin-caribbean', true),
  ('SY', 'Syrie', 'Syrian Arab Republic', 'asia', true),
  ('SZ', 'Eswatini', 'Eswatini', 'africa-south', true),
  ('TC', 'Îles Turques-et-Caïques', 'Turks and Caicos Islands', 'america-latin-caribbean', true),
  ('TD', 'Tchad', 'Chad', 'africa-central', true),
  ('TF', 'Terres australes et antarctiques françaises', 'French Southern Territories', 'africa-east', true),
  ('TG', 'Togo', 'Togo', 'africa-west', true),
  ('TH', 'Thaïlande', 'Thailand', 'asia', true),
  ('TJ', 'Tadjikistan', 'Tajikistan', 'asia', true),
  ('TK', 'Tokelau', 'Tokelau', 'oceania', true),
  ('TL', 'Timor oriental', 'Timor-Leste', 'asia', true),
  ('TM', 'Turkménistan', 'Turkmenistan', 'asia', true),
  ('TN', 'Tunisie', 'Tunisia', 'africa-north', true),
  ('TO', 'Tonga', 'Tonga', 'oceania', true),
  ('TR', 'Turquie', 'Türkiye', 'asia', true),
  ('TT', 'Trinité-et-Tobago', 'Trinidad and Tobago', 'america-latin-caribbean', true),
  ('TV', 'Tuvalu', 'Tuvalu', 'oceania', true),
  ('TW', 'Taïwan', 'Taiwan, Province of China', 'asia', true),
  ('TZ', 'Tanzanie', 'Tanzania, United Republic of', 'africa-east', true),
  ('UA', 'Ukraine', 'Ukraine', 'europe', true),
  ('UG', 'Ouganda', 'Uganda', 'africa-east', true),
  ('UM', 'Îles mineures éloignées des États-Unis', 'United States Minor Outlying Islands', 'oceania', true),
  ('US', 'États-Unis', 'United States', 'america-north', true),
  ('UY', 'Uruguay', 'Uruguay', 'america-latin-caribbean', true),
  ('UZ', 'Ouzbékistan', 'Uzbekistan', 'asia', true),
  ('VA', 'Saint-Siège (Vatican)', 'Holy See (Vatican City State)', 'europe', true),
  ('VC', 'Saint-Vincent-et-les-Grenadines', 'Saint Vincent and the Grenadines', 'america-latin-caribbean', true),
  ('VE', 'Venezuela', 'Venezuela, Bolivarian Republic of', 'america-latin-caribbean', true),
  ('VG', 'Îles Vierges britanniques', 'Virgin Islands, British', 'america-latin-caribbean', true),
  ('VI', 'Îles Vierges américaines', 'Virgin Islands, U.S.', 'america-latin-caribbean', true),
  ('VN', 'Viêt Nam', 'Viet Nam', 'asia', true),
  ('VU', 'Vanuatu', 'Vanuatu', 'oceania', true),
  ('WF', 'Wallis-et-Futuna', 'Wallis and Futuna', 'oceania', true),
  ('WS', 'Samoa', 'Samoa', 'oceania', true),
  ('YE', 'Yémen', 'Yemen', 'asia', true),
  ('YT', 'Mayotte', 'Mayotte', 'africa-east', true),
  ('ZA', 'Afrique du Sud', 'South Africa', 'africa-south', true),
  ('ZM', 'Zambie', 'Zambia', 'africa-east', true),
  ('ZW', 'Zimbabwe', 'Zimbabwe', 'africa-east', true)
on conflict (code) do nothing;

-- ---------------------------------------------------------------------
-- 3. Langues (doc 20 Partie F)
-- ---------------------------------------------------------------------
insert into public.languages (code, name_fr, name_en, sort_order) values
  ('fr', 'Français', 'French', 10),
  ('en', 'Anglais', 'English', 20),
  ('es', 'Espagnol', 'Spanish', 30),
  ('pt', 'Portugais', 'Portuguese', 40),
  ('ar', 'Arabe', 'Arabic', 50),
  ('de', 'Allemand', 'German', 60),
  ('it', 'Italien', 'Italian', 70),
  ('zh', 'Chinois', 'Chinese', 80)
on conflict (code) do nothing;
