-- =====================================================================
-- 0023_seed_taxonomy_skills
-- Seed integral de la taxonomie de competences.
--
--   18 domaines      (doc 20 section 4)
--   92 categories    (84 du doc 20 + 8 categories entieres du doc 19)
--   543 competences   (432 `doc20` + 111 `doc19`)
--   125 alias         (89 du doc 20 + 3 issus de D-63 + 33 variantes doc 19)
--
-- Decisions appliquees :
--   D-60 : l'INTEGRALITE de l'enumeration du doc 20 est seedee (435 lignes
--          comptees), et non le sous-ensemble "environ 220" annonce par le
--          document lui-meme.
--   D-61 : les libelles du doc 19 absents du doc 20 sont integres et marques
--          `source = 'doc19'` pour arbitrage back-office, dont 8 categories
--          entieres (Economie sectorielle, Computer Vision, Recensements,
--          Developpement logiciel, Cloud, Project Monitoring, Gouvernance
--          d'entreprise, Leadership). Sont exclus de cette integration :
--          les libelles traites comme OUTILS par le doc 20 (ODK, KoboToolbox,
--          PostgreSQL, Power BI, QGIS, AWS, Python, Git...), les filieres
--          agricoles (specialisations sectorielles) et les libelles deja
--          couverts par une competence doc 20. Les pures variantes de
--          formulation (traductions anglaises, formes courtes) deviennent des
--          ALIAS, conformement a la regle canonique du doc 19 Partie M :
--          "ne pas creer une competence par formulation".
--   D-62 : les slugs sont uniques PAR TABLE. Les collisions inter-tables
--          (`sql` competence vs outil, `microfinance` competence vs secteur)
--          sont licites et volontaires.
--   D-63 : les trois doublons intra-taxonomie sont inseres une seule fois,
--          le second code devenant un alias du premier :
--            020309 Analyse de survie       <- 110304 Analyse de survie en sante
--            030405 Protection sociale      <- 130501 Analyse des systemes de
--                                              protection sociale
--            160103 Planification strategique
--                                           <- 130201 Planification strategique
--                                              publique
--          Les codes 110304 / 130501 / 130201 ne sont donc PAS inseres.
--   D-46 : `is_short_acronym` marque les alias de moins de 4 caracteres
--          (IE, IV, ML, BI...), resolus uniquement en majuscules et isoles.
--
-- Les identifiants sont `generated always as identity` : aucun `id` explicite
-- n'est insere. Les FK sont resolues par les colonnes `code` (le code d'une
-- categorie est le prefixe de 4 chiffres du code de ses competences, celui
-- d'un domaine le prefixe de 2 chiffres du code de ses categories).
-- Migration de DONNEES uniquement : aucun DDL, aucune modification de RLS.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Domaines (18)
-- ---------------------------------------------------------------------
insert into public.skill_domains (code, name, slug, sort_order) values
  ('01','Statistique et méthodes quantitatives','statistique-methodes-quantitatives',10),
  ('02','Économétrie et modélisation','econometrie-modelisation',20),
  ('03','Économie','economie',30),
  ('04','Data Science, IA et Machine Learning','data-science-ia-machine-learning',40),
  ('05','Enquêtes, recensements et collecte','enquetes-recensements-collecte',50),
  ('06','Suivi-évaluation et mesure d''impact','suivi-evaluation-impact',60),
  ('07','Systèmes d''information et données','systemes-information-donnees',70),
  ('08','Business Intelligence et visualisation','business-intelligence-visualisation',80),
  ('09','Finance, banque et assurance','finance-banque-assurance',90),
  ('10','Agriculture et développement rural','agriculture-developpement-rural',100),
  ('11','Santé, population et démographie','sante-population-demographie',110),
  ('12','Éducation et capital humain','education-capital-humain',120),
  ('13','Politiques publiques et développement','politiques-publiques-developpement',130),
  ('14','Gestion de projets et programmes','gestion-projets-programmes',140),
  ('15','Recherche, études et conseil','recherche-etudes-conseil',150),
  ('16','Management, stratégie et entrepreneuriat','management-strategie-entrepreneuriat',160),
  ('17','Géomatique, SIG et analyse spatiale','geomatique-sig-analyse-spatiale',170),
  ('18','Compétences professionnelles transversales','competences-professionnelles-transversales',180)
on conflict (code) do nothing;

-- ---------------------------------------------------------------------
-- 2. Categories (92)
-- ---------------------------------------------------------------------
insert into public.skill_categories (domain_id, code, name, slug, sort_order)
select dm.id, v.code, v.name, v.slug, (right(v.code, 2))::int * 10
from (values
  ('0101','Statistique descriptive','statistique-descriptive'),
  ('0102','Inférence statistique','inference-statistique'),
  ('0103','Analyse multivariée','analyse-multivariee'),
  ('0104','Séries temporelles','series-temporelles'),
  ('0105','Méthodes avancées','methodes-avancees'),
  ('0201','Économétrie générale','econometrie-generale'),
  ('0202','Données de panel','donnees-de-panel'),
  ('0203','Microéconométrie','microeconometrie'),
  ('0204','Macroéconométrie','macroeconometrie'),
  ('0205','Inférence causale','inference-causale'),
  ('0206','Économétrie spatiale','econometrie-spatiale'),
  ('0301','Macroéconomie','macroeconomie'),
  ('0302','Microéconomie','microeconomie'),
  ('0303','Développement','developpement'),
  ('0304','Économie publique','economie-publique'),
  ('0305','Économie internationale','economie-internationale'),
  ('0306','Économie du travail','economie-du-travail'),
  ('0401','Data Science','data-science'),
  ('0402','Machine Learning','machine-learning'),
  ('0403','Deep Learning','deep-learning'),
  ('0404','IA générative','ia-generative'),
  ('0405','NLP','nlp'),
  ('0406','MLOps','mlops'),
  ('0501','Conception d''enquête','conception-d-enquete'),
  ('0502','Échantillonnage','echantillonnage'),
  ('0503','Collecte de données','collecte-de-donnees'),
  ('0504','Organisation terrain','organisation-terrain'),
  ('0505','Traitement des données d''enquête','traitement-des-donnees-d-enquete'),
  ('0506','Recherche qualitative','recherche-qualitative'),
  ('0601','Suivi-évaluation','suivi-evaluation'),
  ('0602','Évaluation','evaluation'),
  ('0603','Évaluation d''impact','evaluation-d-impact'),
  ('0604','Performance','performance'),
  ('0605','MEL / MEAL','mel-meal'),
  ('0701','Bases de données','bases-de-donnees'),
  ('0702','Data Engineering','data-engineering'),
  ('0703','Architecture SI','architecture-si'),
  ('0704','Transformation digitale','transformation-digitale'),
  ('0801','Visualisation','visualisation'),
  ('0802','Business Intelligence','business-intelligence'),
  ('0803','Dashboards','dashboards'),
  ('0901','Banque','banque'),
  ('0902','Gestion des risques','gestion-des-risques'),
  ('0903','Finance','finance'),
  ('0904','Financement du développement','financement-du-developpement'),
  ('0905','Assurance','assurance'),
  ('0906','FinTech','fintech'),
  ('1001','Économie agricole','economie-agricole'),
  ('1002','Développement rural','developpement-rural'),
  ('1003','Agriculture durable','agriculture-durable'),
  ('1101','Démographie','demographie'),
  ('1102','Santé publique','sante-publique'),
  ('1103','Épidémiologie et biostatistique','epidemiologie-et-biostatistique'),
  ('1104','Économie de la santé','economie-de-la-sante'),
  ('1105','Information sanitaire','information-sanitaire'),
  ('1201','Économie de l''éducation','economie-de-l-education'),
  ('1202','Planification éducative','planification-educative'),
  ('1203','Évaluation des apprentissages','evaluation-des-apprentissages'),
  ('1204','Données éducatives','donnees-educatives'),
  ('1301','Politiques publiques','politiques-publiques'),
  ('1302','Planification et prospective','planification-et-prospective'),
  ('1303','Gouvernance','gouvernance'),
  ('1304','Développement international','developpement-international'),
  ('1305','Protection sociale','protection-sociale'),
  ('1401','Gestion de projet','gestion-de-projet'),
  ('1402','Gestion de programmes','gestion-de-programmes'),
  ('1403','Méthodologies','methodologies'),
  ('1501','Méthodologie de recherche','methodologie-de-recherche'),
  ('1502','Études','etudes'),
  ('1503','Conseil','conseil'),
  ('1504','Production intellectuelle','production-intellectuelle'),
  ('1505','Montage d''études','montage-d-etudes'),
  ('1601','Stratégie','strategie'),
  ('1602','Management','management'),
  ('1603','Entrepreneuriat','entrepreneuriat'),
  ('1604','Développement commercial','developpement-commercial'),
  ('1701','SIG','sig'),
  ('1702','Analyse spatiale','analyse-spatiale'),
  ('1703','Télédétection','teledetection'),
  ('1704','Géolocalisation','geolocalisation'),
  ('1801','Communication','communication'),
  ('1802','Formation','formation'),
  ('1803','Négociation','negociation'),
  ('1804','Rédaction','redaction'),
  ('0307','Économie sectorielle','economie-sectorielle'),
  ('0407','Computer Vision','computer-vision'),
  ('0507','Recensements','recensements'),
  ('0705','Développement logiciel','developpement-logiciel'),
  ('0706','Cloud','cloud'),
  ('1404','Project Monitoring','project-monitoring'),
  ('1605','Gouvernance d''entreprise','gouvernance-d-entreprise'),
  ('1805','Leadership','leadership')
) as v(code, name, slug)
join public.skill_domains dm on dm.code = left(v.code, 2)
on conflict (code) do nothing;

-- ---------------------------------------------------------------------
-- 3. Competences du doc 20 (432, apres deduplication D-63)
-- ---------------------------------------------------------------------
insert into public.skills (category_id, code, name, slug, source)
select ct.id, v.code, v.name, v.slug, 'doc20'
from (values
  ('010101','Statistique descriptive','statistique-descriptive'),
  ('010102','Analyse exploratoire des données','analyse-exploratoire-donnees'),
  ('010103','Construction d''indicateurs statistiques','construction-indicateurs-statistiques'),
  ('010104','Analyse de distributions statistiques','analyse-distributions-statistiques'),
  ('010201','Inférence statistique','inference-statistique'),
  ('010202','Estimation statistique','estimation-statistique'),
  ('010203','Tests d''hypothèses','tests-hypotheses'),
  ('010204','Intervalles de confiance','intervalles-confiance'),
  ('010205','Maximum de vraisemblance','maximum-vraisemblance'),
  ('010206','Méthodes non paramétriques','methodes-non-parametriques'),
  ('010207','Bootstrap','bootstrap'),
  ('010301','Analyse en composantes principales','analyse-composantes-principales'),
  ('010302','Analyse factorielle','analyse-factorielle'),
  ('010303','Analyse des correspondances','analyse-correspondances'),
  ('010304','Analyse des correspondances multiples','analyse-correspondances-multiples'),
  ('010305','Classification statistique','classification-statistique'),
  ('010306','Clustering','clustering'),
  ('010307','Analyse discriminante','analyse-discriminante'),
  ('010308','Réduction de dimension','reduction-dimension'),
  ('010401','Analyse des séries temporelles','analyse-series-temporelles'),
  ('010402','Prévision statistique','prevision-statistique'),
  ('010403','ARIMA','arima'),
  ('010404','SARIMA','sarima'),
  ('010405','Lissage exponentiel','lissage-exponentiel'),
  ('010406','Décomposition saisonnière','decomposition-saisonniere'),
  ('010501','Statistique bayésienne','statistique-bayesienne'),
  ('010502','Modèles bayésiens','modeles-bayesiens'),
  ('010503','Monte Carlo par chaînes de Markov','mcmc'),
  ('010504','Simulation statistique','simulation-statistique'),
  ('020101','Économétrie','econometrie'),
  ('020102','Régression linéaire','regression-lineaire'),
  ('020103','Régression multiple','regression-multiple'),
  ('020104','Variables instrumentales','variables-instrumentales'),
  ('020105','Méthode des moments généralisés','gmm'),
  ('020106','Modèles non linéaires','modeles-non-lineaires'),
  ('020107','Traitement de l''endogénéité','endogeneite'),
  ('020201','Économétrie des données de panel','econometrie-donnees-panel'),
  ('020202','Modèles à effets fixes','modeles-effets-fixes'),
  ('020203','Modèles à effets aléatoires','modeles-effets-aleatoires'),
  ('020204','Panel dynamique','panel-dynamique'),
  ('020205','GMM sur données de panel','gmm-panel'),
  ('020301','Microéconométrie','microeconometrie'),
  ('020302','Modèles Logit','modeles-logit'),
  ('020303','Modèles Probit','modeles-probit'),
  ('020304','Modèles Tobit','modeles-tobit'),
  ('020305','Modèles de choix discret','modeles-choix-discret'),
  ('020306','Modèles multinomiaux','modeles-multinomiaux'),
  ('020307','Modèles ordonnés','modeles-ordonnes'),
  ('020308','Modèles de durée','modeles-duree'),
  ('020309','Analyse de survie','analyse-survie'),
  ('020401','Macroéconométrie','macroeconometrie'),
  ('020402','Modèles VAR','modeles-var'),
  ('020403','Modèles VECM','modeles-vecm'),
  ('020404','Cointégration','cointegration'),
  ('020405','Modèles DSGE','modeles-dsge'),
  ('020406','Prévision macroéconomique','prevision-macroeconomique'),
  ('020501','Inférence causale','inference-causale'),
  ('020502','Essais contrôlés randomisés','essais-controles-randomises'),
  ('020503','Différences-en-différences','differences-differences'),
  ('020504','Régression sur discontinuité','regression-discontinuite'),
  ('020505','Appariement par score de propension','propensity-score-matching'),
  ('020506','Contrôle synthétique','controle-synthetique'),
  ('020507','Causal Machine Learning','causal-machine-learning'),
  ('020601','Économétrie spatiale','econometrie-spatiale'),
  ('020602','Modèles SAR','modeles-sar'),
  ('020603','Modèles SEM spatiaux','modeles-sem-spatiaux'),
  ('020604','Régression géographiquement pondérée','regression-geographiquement-ponderee'),
  ('030101','Macroéconomie','macroeconomie'),
  ('030102','Analyse de la croissance économique','croissance-economique'),
  ('030103','Analyse de l''inflation','analyse-inflation'),
  ('030104','Politique monétaire','politique-monetaire'),
  ('030105','Politique budgétaire','politique-budgetaire'),
  ('030106','Dette publique','dette-publique'),
  ('030107','Analyse macroéconomique','analyse-macroeconomique'),
  ('030201','Microéconomie','microeconomie'),
  ('030202','Organisation industrielle','organisation-industrielle'),
  ('030203','Théorie des jeux','theorie-jeux'),
  ('030204','Économie comportementale','economie-comportementale'),
  ('030301','Économie du développement','economie-developpement'),
  ('030302','Analyse de la pauvreté','analyse-pauvrete'),
  ('030303','Analyse des inégalités','analyse-inegalites'),
  ('030304','Développement humain','developpement-humain'),
  ('030305','Inclusion économique','inclusion-economique'),
  ('030306','Croissance inclusive','croissance-inclusive'),
  ('030401','Économie publique','economie-publique'),
  ('030402','Finances publiques','finances-publiques'),
  ('030403','Fiscalité','fiscalite'),
  ('030404','Analyse des dépenses publiques','analyse-depenses-publiques'),
  ('030405','Protection sociale','protection-sociale'),
  ('030406','Analyse budgétaire','analyse-budgetaire'),
  ('030501','Économie internationale','economie-internationale'),
  ('030502','Commerce international','commerce-international'),
  ('030503','Intégration régionale','integration-regionale'),
  ('030504','Balance des paiements','balance-paiements'),
  ('030505','Taux de change','taux-change'),
  ('030506','Investissement direct étranger','investissement-direct-etranger'),
  ('030507','Compétitivité économique','competitivite-economique'),
  ('030601','Économie du travail','economie-travail'),
  ('030602','Analyse du marché du travail','analyse-marche-travail'),
  ('030603','Emploi et chômage','emploi-chomage'),
  ('030604','Économie informelle','economie-informelle'),
  ('030605','Analyse salariale','analyse-salariale'),
  ('030606','Productivité du travail','productivite-travail'),
  ('040101','Data Science','data-science'),
  ('040102','Data Mining','data-mining'),
  ('040103','Feature Engineering','feature-engineering'),
  ('040104','Modélisation prédictive','modelisation-predictive'),
  ('040105','Préparation des données','preparation-donnees'),
  ('040106','Analyse de données à grande échelle','analyse-donnees-grande-echelle'),
  ('040201','Machine Learning','machine-learning'),
  ('040202','Apprentissage supervisé','apprentissage-supervise'),
  ('040203','Apprentissage non supervisé','apprentissage-non-supervise'),
  ('040204','Random Forest','random-forest'),
  ('040205','Gradient Boosting','gradient-boosting'),
  ('040206','XGBoost','xgboost'),
  ('040207','Support Vector Machines','support-vector-machines'),
  ('040208','Optimisation des hyperparamètres','optimisation-hyperparametres'),
  ('040301','Deep Learning','deep-learning'),
  ('040302','Réseaux de neurones','reseaux-neurones'),
  ('040303','Réseaux convolutifs','cnn'),
  ('040304','Réseaux récurrents','rnn'),
  ('040305','LSTM','lstm'),
  ('040306','Transformers','transformers'),
  ('040401','Intelligence artificielle générative','intelligence-artificielle-generative'),
  ('040402','Large Language Models','large-language-models'),
  ('040403','Prompt Engineering','prompt-engineering'),
  ('040404','Retrieval-Augmented Generation','retrieval-augmented-generation'),
  ('040405','Agents IA','agents-ia'),
  ('040406','Embeddings','embeddings'),
  ('040407','Fine-tuning de modèles','fine-tuning-modeles'),
  ('040408','Évaluation de systèmes IA','evaluation-systemes-ia'),
  ('040501','Traitement automatique du langage naturel','traitement-langage-naturel'),
  ('040502','Text Mining','text-mining'),
  ('040503','Classification de texte','classification-texte'),
  ('040504','Topic Modeling','topic-modeling'),
  ('040505','Analyse de sentiments','analyse-sentiments'),
  ('040601','MLOps','mlops'),
  ('040602','Déploiement de modèles ML','deploiement-modeles-ml'),
  ('040603','Monitoring de modèles','monitoring-modeles'),
  ('040604','Pipelines Machine Learning','pipelines-machine-learning'),
  ('050101','Conception d''enquête','conception-enquete'),
  ('050102','Méthodologie d''enquête','methodologie-enquete'),
  ('050103','Conception de questionnaire','conception-questionnaire'),
  ('050104','Test pilote','test-pilote'),
  ('050105','Protocoles de collecte','protocoles-collecte'),
  ('050201','Échantillonnage','echantillonnage'),
  ('050202','Échantillonnage aléatoire simple','echantillonnage-aleatoire-simple'),
  ('050203','Échantillonnage stratifié','echantillonnage-stratifie'),
  ('050204','Échantillonnage en grappes','echantillonnage-grappes'),
  ('050205','Échantillonnage à plusieurs degrés','echantillonnage-plusieurs-degres'),
  ('050206','Échantillonnage PPS','echantillonnage-pps'),
  ('050207','Calcul de taille d''échantillon','taille-echantillon'),
  ('050208','Pondération d''enquête','ponderation-enquete'),
  ('050209','Calibration des poids','calibration-poids'),
  ('050301','Collecte de données','collecte-donnees'),
  ('050302','Collecte CAPI','collecte-capi'),
  ('050303','Collecte CATI','collecte-cati'),
  ('050304','Collecte CAWI','collecte-cawi'),
  ('050305','Collecte mobile','collecte-mobile'),
  ('050306','Collecte géoréférencée','collecte-georeferencee'),
  ('050401','Organisation d''enquête terrain','organisation-enquete-terrain'),
  ('050402','Formation des enquêteurs','formation-enqueteurs'),
  ('050403','Supervision d''enquête','supervision-enquete'),
  ('050404','Contrôle qualité terrain','controle-qualite-terrain'),
  ('050405','Monitoring de collecte','monitoring-collecte'),
  ('050406','Logistique de collecte','logistique-collecte'),
  ('050501','Apurement des données','apurement-donnees'),
  ('050502','Contrôle de cohérence','controle-coherence'),
  ('050503','Imputation statistique','imputation-statistique'),
  ('050504','Traitement des non-réponses','traitement-non-reponses'),
  ('050505','Tabulation statistique','tabulation-statistique'),
  ('050601','Recherche qualitative','recherche-qualitative'),
  ('050602','Entretien semi-directif','entretien-semi-directif'),
  ('050603','Focus Group','focus-group'),
  ('050604','Analyse de contenu qualitative','analyse-contenu-qualitative'),
  ('050605','Codification qualitative','codification-qualitative'),
  ('060101','Suivi-évaluation','suivi-evaluation'),
  ('060102','Conception d''un système de suivi-évaluation','conception-systeme-suivi-evaluation'),
  ('060103','Plan de suivi-évaluation','plan-suivi-evaluation'),
  ('060104','Cadre de résultats','cadre-resultats'),
  ('060105','Cadre logique','cadre-logique'),
  ('060106','Théorie du changement','theorie-changement'),
  ('060107','Indicateurs de performance','indicateurs-performance'),
  ('060108','Baseline','baseline'),
  ('060109','Endline','endline'),
  ('060201','Évaluation de projets','evaluation-projets'),
  ('060202','Évaluation de programmes','evaluation-programmes'),
  ('060203','Évaluation à mi-parcours','evaluation-mi-parcours'),
  ('060204','Évaluation finale','evaluation-finale'),
  ('060205','Évaluation ex ante','evaluation-ex-ante'),
  ('060206','Évaluation ex post','evaluation-ex-post'),
  ('060301','Évaluation d''impact','evaluation-impact'),
  ('060302','Conception d''évaluation d''impact','conception-evaluation-impact'),
  ('060303','Analyse contrefactuelle','analyse-contrefactuelle'),
  ('060401','Gestion axée sur les résultats','gestion-axee-resultats'),
  ('060402','Mesure de performance institutionnelle','performance-institutionnelle'),
  ('060403','Tableaux de bord de performance','tableaux-bord-performance'),
  ('060404','Conception de KPI','conception-kpi'),
  ('060405','Scorecards','scorecards'),
  ('060501','Monitoring Evaluation and Learning','monitoring-evaluation-learning'),
  ('060502','Monitoring Evaluation Accountability and Learning','meal'),
  ('060503','Learning Agenda','learning-agenda'),
  ('060504','Accountability programme','accountability-programme'),
  ('070101','Modélisation de bases de données','modelisation-bases-donnees'),
  ('070102','SQL','sql'),
  ('070103','Administration de bases de données','administration-bases-donnees'),
  ('070104','Optimisation de requêtes SQL','optimisation-requetes-sql'),
  ('070105','Gouvernance des données','gouvernance-donnees'),
  ('070201','Data Engineering','data-engineering'),
  ('070202','ETL','etl'),
  ('070203','ELT','elt'),
  ('070204','Data Pipelines','data-pipelines'),
  ('070205','Data Warehouse','data-warehouse'),
  ('070206','Data Lake','data-lake'),
  ('070207','Qualité des données','qualite-donnees'),
  ('070208','Master Data Management','master-data-management'),
  ('070301','Architecture des systèmes d''information','architecture-systemes-information'),
  ('070302','Architecture de données','architecture-donnees'),
  ('070303','Architecture applicative','architecture-applicative'),
  ('070304','Intégration de systèmes','integration-systemes'),
  ('070305','Conception d''API','conception-api'),
  ('070306','Interopérabilité des systèmes','interoperabilite-systemes'),
  ('070401','Transformation digitale','transformation-digitale'),
  ('070402','Digitalisation des processus','digitalisation-processus'),
  ('070403','Dématérialisation','dematerialisation'),
  ('070404','Automatisation des processus','automatisation-processus'),
  ('070405','E-Government','e-government'),
  ('080101','Visualisation de données','visualisation-donnees'),
  ('080102','Data Storytelling','data-storytelling'),
  ('080103','Infographie statistique','infographie-statistique'),
  ('080104','Conception de graphiques','conception-graphiques'),
  ('080201','Business Intelligence','business-intelligence'),
  ('080202','Reporting automatisé','reporting-automatise'),
  ('080203','Modélisation BI','modelisation-bi'),
  ('080301','Conception de dashboards','conception-dashboards'),
  ('080302','Dashboard exécutif','dashboard-executif'),
  ('080303','Dashboard opérationnel','dashboard-operationnel'),
  ('080304','Dashboard KPI','dashboard-kpi'),
  ('090101','Banque commerciale','banque-commerciale'),
  ('090102','Banque de détail','banque-detail'),
  ('090103','Banque corporate','banque-corporate'),
  ('090104','Banque digitale','banque-digitale'),
  ('090105','Microfinance','microfinance'),
  ('090106','Inclusion financière','inclusion-financiere'),
  ('090201','Gestion des risques bancaires','gestion-risques-bancaires'),
  ('090202','Risque de crédit','risque-credit'),
  ('090203','Risque de marché','risque-marche'),
  ('090204','Risque opérationnel','risque-operationnel'),
  ('090205','Credit Scoring','credit-scoring'),
  ('090206','Stress Testing','stress-testing'),
  ('090207','Modélisation du risque de crédit','modelisation-risque-credit'),
  ('090301','Analyse financière','analyse-financiere'),
  ('090302','Finance d''entreprise','finance-entreprise'),
  ('090303','Finance de marché','finance-marche'),
  ('090304','Modélisation financière','modelisation-financiere'),
  ('090305','Évaluation d''entreprise','evaluation-entreprise'),
  ('090306','Gestion de portefeuille','gestion-portefeuille'),
  ('090401','Financement du développement','financement-developpement'),
  ('090402','Project Finance','project-finance'),
  ('090403','Partenariats public-privé','partenariats-public-prive'),
  ('090404','Financement d''infrastructures','financement-infrastructures'),
  ('090405','Finance climat','finance-climat'),
  ('090406','Finance durable','finance-durable'),
  ('090501','Assurance','assurance'),
  ('090502','Actuariat','actuariat'),
  ('090503','Tarification actuarielle','tarification-actuarielle'),
  ('090504','Analyse du risque assurantiel','risque-assurantiel'),
  ('090601','FinTech','fintech'),
  ('090602','Paiements digitaux','paiements-digitaux'),
  ('090603','Mobile Money','mobile-money'),
  ('090604','Digital Lending','digital-lending'),
  ('090605','RegTech','regtech'),
  ('100101','Économie agricole','economie-agricole'),
  ('100102','Analyse des filières agricoles','analyse-filieres-agricoles'),
  ('100103','Analyse des chaînes de valeur','analyse-chaines-valeur'),
  ('100104','Analyse des prix agricoles','analyse-prix-agricoles'),
  ('100105','Analyse des marchés agricoles','analyse-marches-agricoles'),
  ('100106','Productivité agricole','productivite-agricole'),
  ('100201','Développement rural','developpement-rural'),
  ('100202','Sécurité alimentaire','securite-alimentaire'),
  ('100203','Analyse des moyens d''existence','moyens-existence'),
  ('100204','Analyse de vulnérabilité','analyse-vulnerabilite'),
  ('100205','Résilience des ménages','resilience-menages'),
  ('100301','Agriculture durable','agriculture-durable'),
  ('100302','Agriculture intelligente face au climat','agriculture-intelligente-climat'),
  ('100303','Agroécologie','agroecologie'),
  ('100304','Adaptation climatique agricole','adaptation-climatique-agricole'),
  ('100305','Agriculture de précision','agriculture-precision'),
  ('110101','Démographie','demographie'),
  ('110102','Analyse démographique','analyse-demographique'),
  ('110103','Analyse de la fécondité','analyse-fecondite'),
  ('110104','Analyse de la mortalité','analyse-mortalite'),
  ('110105','Analyse des migrations','analyse-migrations'),
  ('110106','Projections démographiques','projections-demographiques'),
  ('110201','Santé publique','sante-publique'),
  ('110202','Analyse des systèmes de santé','analyse-systemes-sante'),
  ('110203','Santé maternelle et infantile','sante-maternelle-infantile'),
  ('110204','Nutrition','nutrition'),
  ('110205','Analyse VIH/SIDA','analyse-vih-sida'),
  ('110206','Analyse du paludisme','analyse-paludisme'),
  ('110301','Épidémiologie','epidemiologie'),
  ('110302','Biostatistique','biostatistique'),
  ('110303','Surveillance épidémiologique','surveillance-epidemiologique'),
  ('110401','Économie de la santé','economie-sante'),
  ('110402','Financement de la santé','financement-sante'),
  ('110403','Évaluation économique en santé','evaluation-economique-sante'),
  ('110404','Analyse coût-efficacité','analyse-cout-efficacite'),
  ('110501','Systèmes d''information sanitaire','systemes-information-sanitaire'),
  ('110502','DHIS2','dhis2'),
  ('110503','Évaluation de la qualité des données sanitaires','qualite-donnees-sanitaires'),
  ('120101','Économie de l''éducation','economie-education'),
  ('120102','Financement de l''éducation','financement-education'),
  ('120103','Rendement de l''éducation','rendement-education'),
  ('120201','Planification éducative','planification-educative'),
  ('120202','Carte scolaire','carte-scolaire'),
  ('120203','Projections d''effectifs scolaires','projections-effectifs-scolaires'),
  ('120204','Analyse des flux scolaires','analyse-flux-scolaires'),
  ('120301','Évaluation des apprentissages','evaluation-apprentissages'),
  ('120302','Tests standardisés','tests-standardises'),
  ('120303','Psychométrie','psychometrie'),
  ('120304','Analyse des performances scolaires','performances-scolaires'),
  ('120401','Statistiques éducatives','statistiques-educatives'),
  ('120402','Systèmes d''information de gestion de l''éducation','emis'),
  ('120403','Tableaux de bord éducatifs','tableaux-bord-educatifs'),
  ('130101','Analyse des politiques publiques','analyse-politiques-publiques'),
  ('130102','Formulation de politiques publiques','formulation-politiques-publiques'),
  ('130103','Évaluation de politiques publiques','evaluation-politiques-publiques'),
  ('130104','Policy Design','policy-design'),
  ('130202','Planification nationale','planification-nationale'),
  ('130203','Planification sectorielle','planification-sectorielle'),
  ('130204','Prospective','prospective'),
  ('130205','Construction de scénarios','construction-scenarios'),
  ('130301','Gouvernance publique','gouvernance-publique'),
  ('130302','Réforme administrative','reforme-administrative'),
  ('130303','Décentralisation','decentralisation'),
  ('130304','Gouvernance locale','gouvernance-locale'),
  ('130305','Redevabilité publique','redevabilite-publique'),
  ('130401','Développement international','developpement-international'),
  ('130402','Coopération internationale','cooperation-internationale'),
  ('130403','Aide au développement','aide-developpement'),
  ('130404','Objectifs de développement durable','objectifs-developpement-durable'),
  ('130502','Filets sociaux','filets-sociaux'),
  ('130503','Transferts monétaires','transferts-monetaires'),
  ('130504','Ciblage des bénéficiaires','ciblage-beneficiaires'),
  ('130505','Registres sociaux','registres-sociaux'),
  ('140101','Gestion de projet','gestion-projet'),
  ('140102','Planification de projet','planification-projet'),
  ('140103','Gestion des coûts projet','gestion-couts-projet'),
  ('140104','Gestion des risques projet','gestion-risques-projet'),
  ('140105','Gestion des parties prenantes','gestion-parties-prenantes'),
  ('140106','Gestion de la qualité projet','gestion-qualite-projet'),
  ('140201','Gestion de programmes','gestion-programmes'),
  ('140202','Coordination multi-projets','coordination-multi-projets'),
  ('140203','Gestion de portefeuille de projets','gestion-portefeuille-projets'),
  ('140301','PMP','pmp'),
  ('140302','Agile','agile'),
  ('140303','Scrum','scrum'),
  ('140304','Kanban','kanban'),
  ('140305','PRINCE2','prince2'),
  ('150101','Méthodologie de recherche','methodologie-recherche'),
  ('150102','Revue de littérature','revue-litterature'),
  ('150103','Recherche quantitative','recherche-quantitative'),
  ('150104','Recherche mixte','recherche-mixte'),
  ('150105','Analyse scientifique','analyse-scientifique'),
  ('150201','Études socio-économiques','etudes-socio-economiques'),
  ('150202','Études de marché','etudes-marche'),
  ('150203','Études de faisabilité','etudes-faisabilite'),
  ('150204','Diagnostic socio-économique','diagnostic-socio-economique'),
  ('150205','Analyse situationnelle','analyse-situationnelle'),
  ('150301','Conseil stratégique','conseil-strategique'),
  ('150302','Conseil économique','conseil-economique'),
  ('150303','Conseil en organisation','conseil-organisation'),
  ('150304','Conseil en performance','conseil-performance'),
  ('150305','Conseil en data','conseil-data'),
  ('150401','Rédaction de rapports d''étude','redaction-rapports-etude'),
  ('150402','Rédaction de Policy Briefs','redaction-policy-briefs'),
  ('150403','Publication scientifique','publication-scientifique'),
  ('150404','Rédaction de notes de politique','redaction-notes-politique'),
  ('150405','Synthèse exécutive','synthese-executive'),
  ('150501','Élaboration de termes de référence','elaboration-termes-reference'),
  ('150502','Élaboration de propositions techniques','propositions-techniques'),
  ('150503','Conception méthodologique d''étude','conception-methodologique-etude'),
  ('150504','Coordination d''équipes d''experts','coordination-equipes-experts'),
  ('150505','Gestion de missions de consultance','gestion-missions-consultance'),
  ('160101','Stratégie d''entreprise','strategie-entreprise'),
  ('160102','Stratégie institutionnelle','strategie-institutionnelle'),
  ('160103','Planification stratégique','planification-strategique'),
  ('160104','Business Model','business-model'),
  ('160201','Management','management'),
  ('160202','Leadership','leadership'),
  ('160203','Management d''équipe','management-equipe'),
  ('160204','Conduite du changement','conduite-changement'),
  ('160205','Transformation organisationnelle','transformation-organisationnelle'),
  ('160301','Entrepreneuriat','entrepreneuriat'),
  ('160302','Création d''entreprise','creation-entreprise'),
  ('160303','Développement de startup','developpement-startup'),
  ('160304','Business Plan','business-plan'),
  ('160305','Levée de fonds','levee-fonds'),
  ('160306','Go-to-Market','go-to-market'),
  ('160401','Business Development','business-development'),
  ('160402','Vente B2B','vente-b2b'),
  ('160403','Gestion de partenariats','gestion-partenariats'),
  ('160404','Gestion grands comptes','gestion-grands-comptes'),
  ('160405','Négociation commerciale','negociation-commerciale'),
  ('170101','Systèmes d''information géographique','systemes-information-geographique'),
  ('170102','Cartographie numérique','cartographie-numerique'),
  ('170103','Gestion de données géospatiales','gestion-donnees-geospatiales'),
  ('170201','Analyse spatiale','analyse-spatiale'),
  ('170202','Statistique spatiale','statistique-spatiale'),
  ('170203','Géostatistique','geostatistique'),
  ('170204','Spatial Data Analysis','spatial-data-analysis'),
  ('170301','Télédétection','teledetection'),
  ('170302','Analyse d''imagerie satellitaire','analyse-imagerie-satellitaire'),
  ('170303','Classification d''images satellitaires','classification-images-satellitaires'),
  ('170401','Géocodage','geocodage'),
  ('170402','Analyse GPS','analyse-gps'),
  ('170403','Routing géospatial','routing-geospatial'),
  ('180101','Communication professionnelle','communication-professionnelle'),
  ('180102','Présentation professionnelle','presentation-professionnelle'),
  ('180103','Prise de parole en public','prise-parole-public'),
  ('180104','Facilitation d''atelier','facilitation-atelier'),
  ('180201','Formation professionnelle','formation-professionnelle'),
  ('180202','Conception pédagogique','conception-pedagogique'),
  ('180203','Formation de formateurs','formation-formateurs'),
  ('180204','Coaching professionnel','coaching-professionnel'),
  ('180301','Négociation','negociation'),
  ('180302','Médiation','mediation'),
  ('180303','Gestion des conflits','gestion-conflits'),
  ('180401','Rédaction professionnelle','redaction-professionnelle'),
  ('180402','Rédaction technique','redaction-technique'),
  ('180403','Rédaction scientifique','redaction-scientifique'),
  ('180404','Rédaction de propositions','redaction-propositions')
) as v(code, name, slug)
join public.skill_categories ct on ct.code = left(v.code, 4)
on conflict (code) do nothing;

-- ---------------------------------------------------------------------
-- 4. Competences du doc 19 absentes du doc 20 (111) - D-61
-- ---------------------------------------------------------------------
insert into public.skills (category_id, code, name, slug, source)
select ct.id, v.code, v.name, v.slug, 'doc19'
from (values
  ('010151','Mesures de tendance centrale','mesures-de-tendance-centrale'),
  ('010152','Mesures de dispersion','mesures-de-dispersion'),
  ('010251','Inférence paramétrique','inference-parametrique'),
  ('010252','Inférence non paramétrique','inference-non-parametrique'),
  ('010253','Tests statistiques','tests-statistiques'),
  ('010254','Tests de rang','tests-de-rang'),
  ('010255','Jackknife','jackknife'),
  ('010256','Statistique non paramétrique','statistique-non-parametrique'),
  ('010257','Kernel estimation','kernel-estimation'),
  ('010351','Statistiques multidimensionnelles descriptives','statistiques-multidimensionnelles-descriptives'),
  ('010352','Analyse canonique','analyse-canonique'),
  ('010451','Modèles dynamiques','modeles-dynamiques'),
  ('010551','Inférence bayésienne','inference-bayesienne'),
  ('010552','Réseaux bayésiens','reseaux-bayesiens'),
  ('010553','Bayesian forecasting','bayesian-forecasting'),
  ('020151','Moindres carrés','moindres-carres'),
  ('020451','Modèles macroéconomiques','modeles-macroeconomiques'),
  ('020551','Matching causal','matching-causal'),
  ('020552','Expériences randomisées','experiences-randomisees'),
  ('020651','Données géoréférencées','donnees-georeferencees'),
  ('020652','Régression spatiale','regression-spatiale'),
  ('030151','Inflation','inflation'),
  ('030152','Équilibres macroéconomiques','equilibres-macroeconomiques'),
  ('030153','Prévisions macroéconomiques','previsions-macroeconomiques'),
  ('030251','Théorie du consommateur','theorie-du-consommateur'),
  ('030252','Théorie du producteur','theorie-du-producteur'),
  ('030351','Pauvreté','pauvrete'),
  ('030352','Inégalités','inegalites'),
  ('030353','Redistribution','redistribution'),
  ('030651','Marché du travail','marche-du-travail'),
  ('030652','Emploi','emploi'),
  ('030653','Chômage','chomage'),
  ('030654','Informalité','informalite'),
  ('030655','Salaires','salaires'),
  ('030656','Politiques d''emploi','politiques-d-emploi'),
  ('030701','Économie numérique','economie-numerique'),
  ('030702','Économie des transports','economie-des-transports'),
  ('030703','Économie de l''énergie','economie-de-l-energie'),
  ('030704','Économie environnementale','economie-environnementale'),
  ('030705','Économie industrielle','economie-industrielle'),
  ('040151','Analyse de données','analyse-de-donnees'),
  ('040251','Classification prédictive','classification-predictive'),
  ('040252','Régression prédictive','regression-predictive'),
  ('040253','Arbres de décision','arbres-de-decision'),
  ('040551','Analyse de texte','analyse-de-texte'),
  ('040651','Model Registry','model-registry'),
  ('040701','Vision par ordinateur','vision-par-ordinateur'),
  ('040702','Classification d''images','classification-d-images'),
  ('040703','Détection d''objets','detection-d-objets'),
  ('040704','Reconnaissance d''images','reconnaissance-d-images'),
  ('050151','Plan d''enquête','plan-d-enquete'),
  ('050152','Questionnaire','questionnaire'),
  ('050451','Gestion des équipes terrain','gestion-des-equipes-terrain'),
  ('050551','Production d''indicateurs','production-d-indicateurs'),
  ('050651','Analyse qualitative','analyse-qualitative'),
  ('050652','Analyse de contenu','analyse-de-contenu'),
  ('050701','Recensement général','recensement-general'),
  ('050702','Recensement de la population','recensement-de-la-population'),
  ('050703','Recensement agricole','recensement-agricole'),
  ('050704','Recensement économique','recensement-economique'),
  ('050705','Cartographie censitaire','cartographie-censitaire'),
  ('060351','Matching','matching'),
  ('060451','Performance publique','performance-publique'),
  ('060452','KPI','kpi'),
  ('060551','Apprentissage programme','apprentissage-programme'),
  ('060552','Accountability','accountability'),
  ('070151','Modélisation relationnelle','modelisation-relationnelle'),
  ('070451','BPM','bpm'),
  ('070501','Développement web','developpement-web'),
  ('070502','Développement mobile','developpement-mobile'),
  ('070503','JavaScript','javascript'),
  ('070504','TypeScript','typescript'),
  ('070505','R Shiny','r-shiny'),
  ('070506','APIs','apis'),
  ('070601','Cloud Computing','cloud-computing'),
  ('080251','Reporting dynamique','reporting-dynamique'),
  ('090251','Gestion des risques','gestion-des-risques'),
  ('090252','Scoring','scoring'),
  ('090551','Gestion des sinistres','gestion-des-sinistres'),
  ('100251','Agriculture familiale','agriculture-familiale'),
  ('100252','Vulnérabilité','vulnerabilite'),
  ('100253','Résilience','resilience'),
  ('110151','Tables de mortalité','tables-de-mortalite'),
  ('110152','Migration','migration'),
  ('110251','Systèmes de santé','systemes-de-sante'),
  ('110252','Santé maternelle','sante-maternelle'),
  ('110253','Santé infantile','sante-infantile'),
  ('110254','VIH','vih'),
  ('110255','Paludisme','paludisme'),
  ('110256','Maladies non transmissibles','maladies-non-transmissibles'),
  ('110351','Surveillance sanitaire','surveillance-sanitaire'),
  ('120151','Analyse coûts-bénéfices','analyse-couts-benefices'),
  ('120251','Gestion des flux scolaires','gestion-des-flux-scolaires'),
  ('120451','Systèmes d''information scolaire','systemes-d-information-scolaire'),
  ('130251','Scénarios de développement','scenarios-de-developpement'),
  ('130351','Transparence','transparence'),
  ('130451','Institutions de développement','institutions-de-developpement'),
  ('140151','Gestion de délais','gestion-de-delais'),
  ('140401','Planification opérationnelle','planification-operationnelle'),
  ('140402','Workplan','workplan'),
  ('140403','Budget tracking','budget-tracking'),
  ('140404','Risk register','risk-register'),
  ('140405','Project reporting','project-reporting'),
  ('150451','Articles scientifiques','articles-scientifiques'),
  ('160251','Management interculturel','management-interculturel'),
  ('160451','Marketing','marketing'),
  ('160501','Gouvernance d''entreprise','gouvernance-d-entreprise'),
  ('160502','Conseil d''administration','conseil-d-administration'),
  ('160503','Audit stratégique','audit-strategique'),
  ('160504','Gestion de la performance','gestion-de-la-performance'),
  ('180501','Mentorat','mentorat')
) as v(code, name, slug)
join public.skill_categories ct on ct.code = left(v.code, 4)
on conflict (code) do nothing;

-- ---------------------------------------------------------------------
-- 5. Alias (125)
-- ---------------------------------------------------------------------
-- `is_short_acronym` est une colonne GENERATED ALWAYS (length(normalized_alias) < 4)
-- et n'est donc jamais inseree explicitement.
insert into public.skill_aliases (skill_id, alias, normalized_alias)
select sk.id, v.alias, public.normalize_text(v.alias)
from (values
  ('010102','Exploratory Data Analysis'),
  ('010102','EDA'),
  ('010205','Maximum Likelihood'),
  ('010205','MLE'),
  ('010301','ACP'),
  ('010301','Principal Component Analysis'),
  ('010301','PCA'),
  ('010303','AFC'),
  ('010303','Correspondence Analysis'),
  ('010304','ACM'),
  ('010304','Multiple Correspondence Analysis'),
  ('010304','MCA'),
  ('010503','MCMC'),
  ('010503','Markov Chain Monte Carlo'),
  ('020101','Econometrics'),
  ('020105','GMM'),
  ('020105','Generalized Method of Moments'),
  ('020104','Instrumental Variables'),
  ('020104','IV'),
  ('020201','Panel Data Econometrics'),
  ('020202','Fixed Effects'),
  ('020203','Random Effects'),
  ('020502','RCT'),
  ('020502','Randomized Controlled Trial'),
  ('020503','DID'),
  ('020503','Difference-in-Differences'),
  ('020504','RDD'),
  ('020504','Regression Discontinuity Design'),
  ('020505','PSM'),
  ('020505','Propensity Score Matching'),
  ('020506','Synthetic Control'),
  ('020604','GWR'),
  ('020604','Geographically Weighted Regression'),
  ('030506','IDE'),
  ('030506','FDI'),
  ('030506','Foreign Direct Investment'),
  ('040201','ML'),
  ('040201','Apprentissage automatique'),
  ('040207','SVM'),
  ('040303','CNN'),
  ('040303','Convolutional Neural Networks'),
  ('040304','RNN'),
  ('040304','Recurrent Neural Networks'),
  ('040401','Generative AI'),
  ('040401','GenAI'),
  ('040401','IA générative'),
  ('040402','LLM'),
  ('040402','LLMs'),
  ('040404','RAG'),
  ('040405','AI Agents'),
  ('040501','NLP'),
  ('040501','TALN'),
  ('040501','Natural Language Processing'),
  ('050206','Probability Proportional to Size'),
  ('050206','PPS'),
  ('060101','Monitoring and Evaluation'),
  ('060101','Monitoring & Evaluation'),
  ('060101','M&E'),
  ('060101','S&E'),
  ('060106','Theory of Change'),
  ('060106','ToC'),
  ('060301','Impact Evaluation'),
  ('060301','IE'),
  ('060401','GAR'),
  ('060401','RBM'),
  ('060401','Results-Based Management'),
  ('060501','MEL'),
  ('060502','MEAL'),
  ('070208','MDM'),
  ('080201','BI'),
  ('090403','PPP'),
  ('090403','Public-Private Partnership'),
  ('100203','Livelihoods'),
  ('100302','Climate-Smart Agriculture'),
  ('100302','CSA'),
  ('110404','Cost-Effectiveness Analysis'),
  ('110404','CEA'),
  ('120402','EMIS'),
  ('120402','Education Management Information System'),
  ('130404','ODD'),
  ('130404','SDG'),
  ('130404','Sustainable Development Goals'),
  ('150501','TDR'),
  ('150501','Terms of Reference'),
  ('150501','ToR'),
  ('170101','SIG'),
  ('170101','GIS'),
  ('170101','Geographic Information Systems'),
  ('170301','Remote Sensing'),
  ('020309','Analyse de survie en santé'),
  ('030405','Analyse des systèmes de protection sociale'),
  ('160103','Planification stratégique publique'),
  ('030102','Croissance économique'),
  ('040505','Sentiment Analysis'),
  ('060405','Scorecard'),
  ('020504','Régression discontinue'),
  ('090207','Credit Risk Modeling'),
  ('090106','Financial Inclusion'),
  ('100203','Moyens d''existence'),
  ('110501','Health Information Systems'),
  ('110503','Data Quality Assessment'),
  ('120403','Tableau de bord éducation'),
  ('130101','Policy Analysis'),
  ('130103','Policy Evaluation'),
  ('130505','Registre social'),
  ('150401','Rédaction de rapports'),
  ('150402','Policy briefs'),
  ('150404','Notes de politique'),
  ('150502','Proposition technique'),
  ('150501','Élaboration de TDR'),
  ('160101','Business Strategy'),
  ('160103','Strategic Planning'),
  ('160303','Startup'),
  ('160401','Développement commercial'),
  ('160403','Partenariats'),
  ('170302','Imagerie satellitaire'),
  ('170402','GPS'),
  ('170401','Geocoding'),
  ('170403','Routing'),
  ('180102','Présentation'),
  ('180103','Prise de parole'),
  ('180104','Facilitation'),
  ('180104','Animation d''atelier'),
  ('180201','Formation'),
  ('180204','Coaching')
) as v(skill_code, alias)
join public.skills sk on sk.code = v.skill_code
on conflict (normalized_alias) do nothing;
